# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'verbose_name_plural': 'Page Views'},
        ),
    ]
