#!/bin/bash
echo ""
echo "***** Coosta Run migrations script *****"
date

if [ "$DEPLOYMENT_GROUP_NAME" == "Coosta-dev-Deployment-Group" ]
then
    export build_environment=dev
fi

if [ "$DEPLOYMENT_GROUP_NAME" == "Coosta-QA-Deployment-Group" ]
then
    export build_environment=QA
fi

if [ "$DEPLOYMENT_GROUP_NAME" == "Coosta-prod-Deployment-Group" ]
then
    export build_environment=PROD
fi

echo "build_environment --> ${build_environment}"

echo "Runnig --> docker exec coosta-server bash -c 'cd /home/coosta/coosta;yes "yes" | python manage.py migrate'"
docker exec coosta-server bash -c 'cd /home/coosta/coosta;yes "yes" | python manage.py migrate'
