# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0028_shortlistedproperty_shortlisted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_seller', models.BooleanField(default=False)),
                ('signed_by_buyer', models.BooleanField(default=False)),
                ('signed_by_seller_on', models.DateTimeField(blank=True, null=True)),
                ('signed_by_buyer_on', models.DateTimeField(blank=True, null=True)),
                ('signed_by_seller_at', models.CharField(blank=True, max_length=200, null=True)),
                ('signed_by_buyer_at', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
