# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0028_shortlistedproperty_shortlisted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_raised_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('flag_raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'Flagged Properties',
            },
        ),
        migrations.CreateModel(
            name='FlagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Flag Types',
            },
        ),
        migrations.AddField(
            model_name='flaggedproperty',
            name='type_of_flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.FlagType'),
        ),
    ]
