# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openhousersvp',
            options={'verbose_name_plural': 'OpenHouseRSVPs'},
        ),
    ]
