# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0028_shortlistedproperty_shortlisted_on'),
        ('appointments', '0002_auto_20170417_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by_seller', models.BooleanField(default=False)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('rejected_by_seller', models.BooleanField(default=False)),
                ('rejected_on', models.DateField(blank=True, null=True)),
                ('cancelled_by_buyer', models.BooleanField(default=False)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointment Requests',
            },
        ),
        migrations.CreateModel(
            name='OwnerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('wkd_start_time', models.TimeField(blank=True, null=True)),
                ('wkd_end_time', models.TimeField(blank=True, null=True)),
                ('wknd_start_time', models.TimeField(blank=True, null=True)),
                ('wknd_end_time', models.TimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'OwnerAvailabilities',
            },
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='owner_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.OwnerAvailability'),
        ),
    ]
