# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_super_user(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    from django.contrib.auth.models import User
    User.objects.create_superuser('coosta', 'coosta@mydomain.com', 'demomode')
    User.objects.create_superuser('coosta_admin',
                                  'coosta_admin@mydomain.com',
                                  'demomode')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(upload_to='C:\\Users\\Avinash.Mallik\\Documents\\repos\\Coosta\\coosta/static/uploads/user_profile')),
                ('area_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('town', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RunPython(create_super_user),
    ]
