# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_users', '0005_auto_20161118_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
