# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coosta_users', '0006_auto_20161118_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPreApprovedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Non-Pre-Approved User')),
            ],
            options={
                'verbose_name_plural': 'Non Pre-Approved User',
            },
        ),
    ]
