# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coosta_users', '0007_nonpreapproveduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovedDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='Images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pre-Approved Document User')),
            ],
            options={
                'verbose_name_plural': 'Pre-Approved Documents',
            },
        ),
        migrations.AlterField(
            model_name='nonpreapproveduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Non Pre-Approved User'),
        ),
    ]
