# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_users', '0008_auto_20170421_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproveddocuments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='UserDocuments/'),
        ),
    ]
