# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_users', '0010_preapproveduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproveddocuments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coosta_users.PreApprovedUser', verbose_name='Pre-Approved Document User'),
        ),
    ]
