# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_users', '0011_auto_20170421_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='UserDocuments/')),
            ],
            options={
                'verbose_name_plural': 'User Documents',
            },
        ),
        migrations.AlterField(
            model_name='preapproveddocuments',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_document', to='coosta_users.Documents'),
        ),
    ]
