# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_users', '0012_auto_20170421_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapproveduser',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='pre_approved_documents', through='coosta_users.PreApprovedDocuments', to='coosta_users.Documents'),
        ),
    ]
