# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_users', '0014_auto_20170421_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproveduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
