# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
