# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20161119_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, to='properties.PropertyImages'),
        ),
    ]
