# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20161119_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
