# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20161119_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listed_on',
            field=models.DateField(auto_created=True, blank=True, default='2016-11-20', null=True),
        ),
    ]
