# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20161122_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, through='properties.PropertyImages', to='properties.Images'),
        ),
    ]
