# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='property_images', through='properties.PropertyImages', to='properties.Images'),
        ),
    ]
