# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20161122_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='search_index',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
