# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20161226_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listed_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
