# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='CENTER_LAT',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='CENTER_LON',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
