# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20170212_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='AIN',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
