# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20170219_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
