# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
