# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_property_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
