# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='shortlisted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
