# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_closed_by_escrow', models.BooleanField(default=False)),
                ('deal_closed_by_escrow_on', models.DateTimeField(blank=True, null=True)),
                ('escrow_name', models.CharField(blank=True, max_length=100, null=True)),
                ('escrow_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract')),
            ],
            options={
                'verbose_name_plural': 'Escrow Properties',
            },
        ),
    ]
