# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coosta_message',
            name='create_on',
            field=models.DateTimeField(auto_created=True, blank=True, max_length=10, null=True),
        ),
    ]
