# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_messages', '0002_auto_20161123_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coosta_message',
            name='create_on',
        ),
    ]
