# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coosta_messages', '0003_remove_coosta_message_create_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='coosta_message',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
