# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0028_shortlistedproperty_shortlisted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_offer_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('counter_offer_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counter Offers',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('offer_date', models.DateField(auto_now_add=True, null=True)),
                ('highest_offer_amount', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('final_accepted_offer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.CounterOffers')),
                ('offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AddField(
            model_name='counteroffers',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Offers'),
        ),
        migrations.AddField(
            model_name='counteroffers',
            name='offered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
