# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
